// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bqxaiibbcpbhacwkqxkr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJxeGFpaWJiY3BiaGFjd2txeGtyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjMxMjcyNzcsImV4cCI6MjA3ODcwMzI3N30.lFBwouxgA_moXnVgGEwZhwwo-javsToRn4D4bnB5Yz4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});